Redo PR: Update running-air-gapped.md for MS Windows installation
rancher-sandbox/docs.rancherdesktop.io pull request #111
Opened 2022-10-18 19:19 UTC by ericpromislow

Created a local PR for PR #108 because the original writer wasn't acting on it.

The PR needed to be rebased, and there were typos and stylistic issues as well. It seemed faster to just recreate a PR from his.

2022-10-18 19:28 UTC, jandubois commented
Please give original author @dealboy credit in the commit message (with name and email address) and mention that the original commits all had DCO signoff!

2022-10-18 19:32 UTC, ericpromislow commented
Done.

2022-10-18 21:37 UTC, btat requested changes

2022-10-18 21:37 UTC, btat commented on docs/how-to-guides/running-air-gapped.md
> +### A Note for Windows users
```suggestion
### A Note for Windows Users
```

2022-10-19 20:37 UTC, btat approved these changes

2022-10-19 22:29 UTC, merged