Added a section about the Allowed Images feature
rancher-sandbox/docs.rancherdesktop.io pull request #122
Opened 2022-11-25 22:56 UTC by gunamata

Signed-off-by: Gunasekhar Matamalam <gunasekhar.matamalam@suse.com>

2022-11-25 23:36 UTC, btat requested changes
LGTM. Just a few small nits.

2022-11-25 23:36 UTC, btat commented on docs/ui/preferences/container-engine.md
> +> * `registryServerUrl` defaults to DockerHub registry (`registry-1.docker.io`)
```suggestion
> * `registryServerUrl` defaults to DockerHub registry (`registry-1.docker.io`).
```

Other bullets have a period.

2022-11-25 23:36 UTC, btat commented on docs/ui/preferences/container-engine.md
> +> * `organization` for DockerHub registry defaults to `library`, and for Non-DockerHub registries defaults to no organization.
```suggestion
> * `organization` for DockerHub registry defaults to `library`, and for non-DockerHub registries defaults to no organization.
```

2022-11-25 23:36 UTC, btat commented on docs/ui/preferences/container-engine.md
> +You can use the `+` and `-` buttons to add/remove image URL patterns.
```suggestion
You can use the **+** and **-** buttons to add/remove image URL patterns. 
```

The same formatting as `Enable` above should be used here.

2022-11-25 23:36 UTC, btat commented on docs/ui/preferences/container-engine.md
> +> * `tag` defaults to anything (not including a '/') and NOT just to "latest".
Is the `/` supposed to be formatted/enclosed with backticks instead of single quotes? In other instances, double quotes are used for quoting.

2022-11-28 17:59 UTC, gunamata commented
@btat , I have fixed punctuation/language based on your feedback.

2022-11-28 18:04 UTC, btat approved these changes

2022-11-30 19:47 UTC, merged