How to guide for increasing the open file limit on macOS, Linux, and …
rancher-sandbox/docs.rancherdesktop.io pull request #157
Opened 2023-03-01 23:01 UTC by sunilarjun

…Windows. Written for all versions and updated the versions sidebar as well. This PR fixes #74 .

2023-03-07 05:12 UTC, gunamata requested changes
Proposed some changes to have a consistent tone (second person) and minor rephrasing to improve readability. If agree with the proposals then please apply the changes to other versions too.

2023-03-07 05:12 UTC, gunamata commented on docs/how-to-guides/increasing-open-file-limit.md
> +Users will then have access to the `%AppData%\rancher-desktop\provisioning` directory. Next, please create a file in this directory that will hold the script to update the open file limit by increasi
```suggestion
You can then create a provisioning script, say `map_count.start`, at `%AppData%\rancher-desktop\provisioning` with the below code to update the open file limit by increasing the `max_map_count` parameter.
```

2023-03-07 05:12 UTC, gunamata commented on docs/how-to-guides/increasing-open-file-limit.md
> +Implement the script below in your created `*.start` file.
```suggestion
```

2023-03-07 16:38 UTC, sunilarjun commented
Updated all versions with recommended changes, thank you for the review Guna! If all looks good I can go ahead and merge the changes.

2023-03-08 15:57 UTC, gunamata approved these changes
LGTM, Thank you.

2023-03-08 16:13 UTC, merged