v1.8 Rancher Desktop Documentation Release
rancher-sandbox/docs.rancherdesktop.io pull request #160
Opened 2023-03-09 21:41 UTC by sunilarjun

Updated the dependency list, uploaded macOS/Linux/Windows images to s3 and updated links in latest versions/chinese version.

2023-03-10 09:23 UTC, nunix reviewed
The content is good. 

Please delete the directories `img/preferences` and `img/ui-main` from `/docs`, `/versioned_docs/version-1.8` and `/versioned_docs/version-latest` as it's a redundancy from the S3 images and are no more used.

2023-03-10 17:00 UTC, jandubois commented
I haven't had time to look at this, but in the future please don't mix content changes with structural changes. At the very least they should be separate commits.

Structural changes are things like:
* modifying whitespace / indentation
* everything that is just a global search & replace, e.g. updating version strings in links
* moving files around or duplicating files

During a review it is very hard to find any content edits (or new content) mixed in with structural changes of over 200 files...

2023-03-14 16:16 UTC, jandubois requested changes
`helm` and `trivy` have been updated again since this PR was created.

2023-03-14 16:32 UTC, sunilarjun commented on i18n/zh/docusaurus-plugin-content-docs/version-latest/bundled-utilities-version-info/v1.8.0.md
> +trivy: 0.38.1 <br/>
I'll go ahead and get these updated thank you Jan, also I checked `trivy` again and they've just released a 0.38.3 version today, I will get this updated asap!

2023-03-15 00:25 UTC, sunilarjun commented
The most recent commit addresses PR 162(https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/162) so as to not create a merge conflict. The application.md page has been updated with new verbiage/images for versions next, latest, and v1.8.

2023-03-17 00:13 UTC, gunamata approved these changes
Tested the PR locally and it looks good to me, except for the double shadowed macOS images for 1.7 version docs, which we need to investigate after the release.

2023-03-17 06:05 UTC, jandubois approved these changes

2023-03-17 06:05 UTC, merged