docs: Rancher UI on Rancher Desktop
rancher-sandbox/docs.rancherdesktop.io pull request #21
Opened 2022-02-08 22:51 UTC by evertonlperes

### Changes
1. Created a new section: `Examples`
2. Added an initial how to, installing Rancher UI on Rancher Desktop.

2022-02-08 22:56 UTC, evertonlperes commented
@gunamata 
I'm opening this draft with a new section called `Examples`. This section has the objective to provide some use cases to the users for local development.

2022-02-09 17:11 UTC, gunamata commented
yes, these examples are helpful.. we need to decide on the section title though, whether to call it `Tutorial` or `Examples`.. 

for example, I have another  #6  open where I wrote a doc on how to use VS Code remote containers with RD.. I used the `Tutorial` as the section title though.

2022-02-09 17:16 UTC, evertonlperes commented
> yes, these examples are helpful.. we need to decide on the section title though, whether to call it `Tutorial` or `Examples`..
> 
> for example, I have another #6 open where I wrote a doc on how to use VS Code remote containers with RD.. I used the `Tutorial` as the section title though.

Oh I see, cool.
I'll let your tutorial get merged first and I can modify mine with the correct title and such. Thanks for the heads up.

Thanks @jtravee for adding the labels, I missed to include those 🤣

2022-02-24 16:52 UTC, jtravee requested changes

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Installing Rancher Dashboard on Rancher Desktop using `container runtime` or `helm` (local environment):
```suggestion
To install Rancher Dashboard on Rancher Desktop using `container runtime` or `helm` (local environment):
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 1: Add jetstack charts
```suggestion
1: Add Jetstack charts:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 2: Add rancher lastest charts
```suggestion
2: Add latest Rancher charts:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 3: Create cert-manager namespace
```suggestion
3: Create cert-manager namespace:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 4: Install cert-manager services
```suggestion
4: Install cert-manager services:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 5: Create cattle-system namespace
```suggestion
5: Create cattle-system namespace:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 6: Install Rancher application
```suggestion
6: Install Rancher application:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +The installation takes a few minutes to complete. After the installation, you can access Rancher UI:
```suggestion
The installation takes a few minutes to complete. After the installation, you can access the Rancher UI as follows: 
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 1: Get Rancher UI container ID/Name
```suggestion
1: Get Rancher UI container ID/Name:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 2: Get the Bootstrap Password
```suggestion
2: Get the Bootstrap Password:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 3: Bootstrap Password example
```suggestion
3: Bootstrap Password example:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 1: Get Rancher UI container ID/Name
```suggestion
1: Get Rancher UI container ID/Name:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 2: Get the Bootstrap Password
```suggestion
2: Get the Bootstrap Password:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Step 3: Bootstrap Password example
```suggestion
3: Bootstrap Password example:
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +Follow the wizard instructions and click on `Continue`, to land on the main Rancher UI page.
```suggestion
Follow the wizard instructions and click on `Continue` to land on the main Rancher UI page.
```

2022-02-24 16:52 UTC, jtravee commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +From the Rancher UI you can manage your local cluster, node and more. For more information, see [Rancher Docs](https://rancher.com/docs/).
```suggestion
From the Rancher UI, you can manage your local cluster, node, and more. For more information, see [Rancher Docs](https://rancher.com/docs/).
```

2022-02-24 17:25 UTC, evertonlperes commented on docs/tutorials/rancher-ui-on-rancher-desktop.md
> +2: Add lastest Rancher charts:
Oh boy.. my bad!
Thanks for catching it :D

2022-02-25 22:10 UTC, gunamata approved these changes

2022-02-25 22:11 UTC, merged