Extensions - Remove Details from Documentation
rancher-sandbox/docs.rancherdesktop.io pull request #218
Opened 2023-05-22 20:47 UTC by sunilarjun

The primary goal of this PR is to remove the details page mentions from the extensions UI page and the how-to guide for installing/uninstalling extensions. Made some minor language changes as well due to the update, and will be updating the screenshots with a subsequent PR for the respective operating systems.

2023-05-25 22:41 UTC, gunamata requested changes
I made some minor proposals to improve readability, avoid ambiguity etc. I may not have modified in all the versions. If you agree with my proposals, I will let you apply the changes at all required places.

2023-05-25 22:41 UTC, gunamata commented on docs/how-to-guides/installing-uninstalling-extensions.md
> +Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use which can be downloaded using the **Install** button.
```suggestion
Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use which can be downloaded and installed using the **Install** button.
```

2023-05-25 22:41 UTC, gunamata commented on docs/how-to-guides/installing-uninstalling-extensions.md
> +Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use which can be downloaded using the **Install** button.
```suggestion
Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use which can be downloaded and installed using the **Install** button.
```

2023-05-25 22:41 UTC, gunamata commented on docs/how-to-guides/installing-uninstalling-extensions.md
> +Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use which can be downloaded using the **Install** button.
```suggestion
Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use which can be downloaded and installed using the **Install** button.
```

2023-05-25 22:41 UTC, gunamata commented on docs/how-to-guides/installing-uninstalling-extensions.md
> +Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use, and extensions which have been downloaded can be uninstalled from t
```suggestion
Click **Extensions** from the main UI to navigate to the **Catalog** tab. On this view, you can search through the available extensions, and uninstall the already installed extensions.
```

2023-05-25 22:41 UTC, gunamata commented on docs/how-to-guides/installing-uninstalling-extensions.md
> +Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use, and extensions which have been downloaded can be uninstalled from t
```suggestion
Click **Extensions** from the main UI to navigate to the **Catalog** tab. On this view, you can search through the available extensions, and uninstall the already installed extensions.
```

2023-05-25 22:41 UTC, gunamata commented on docs/how-to-guides/installing-uninstalling-extensions.md
> +Click **Extensions** from the main UI to navigate to the **Catalog** tab. Here you can search through extensions available for use, and extensions which have been downloaded can be uninstalled from t
```suggestion
Click **Extensions** from the main UI to navigate to the **Catalog** tab. On this view, you can search through the available extensions, and uninstall the already installed extensions.
```

2023-05-26 17:08 UTC, sunilarjun commented
Thanks for the review Guna! Updated the language with the proposed changes.

2023-05-29 16:18 UTC, gunamata approved these changes
LGTM, Thank you

2023-05-29 16:19 UTC, merged