Update namespace clarity
rancher-sandbox/docs.rancherdesktop.io pull request #33
Opened 2022-02-26 04:30 UTC by nayrnet

Update documentation to be more clear on the use of the `k8s.io` namespace, and include an example for building containers for k8s.

2022-02-26 04:42 UTC, Bouldersky commented
I showed up in slack asking for help due to confusion with this namespace behavior, and FWIW as a new user to containerd/nerdctl (on top of rancher), I think this change makes the docs much more useful for people like me. 

Thanks @nayrnet both for the help in slack, and for getting this PR out so promptly!

2022-02-28 17:07 UTC, gunamata commented
DCO check seems to be failing. 
@nayrnet , Can you please sign your commit using `--signoff` flag? Thank you for the PR.

2022-02-28 17:55 UTC, gunamata commented on docs/how-to-guides/working-with-images.md
> +Unlike docker, containerd features its own namespaces, by default images are stored in the `default` namespace.
Can we add these statements without removing the earlier statements, as I feel your steps/statements compliment the original information here.

2022-03-01 16:10 UTC, jtravee requested changes

2022-03-01 16:10 UTC, jtravee commented on docs/how-to-guides/working-with-images.md
> +The Kubernetes images are stored in the `k8s.io` namespace. If you want your images avilable for use by Kubernetes
As per Guna's note, if you keep the original verbiage, you can remove the first sentence here.

2022-03-01 16:10 UTC, jtravee commented on docs/how-to-guides/working-with-images.md
> +The Kubernetes images are stored in the `k8s.io` namespace. If you want your images avilable for use by Kubernetes
```suggestion
If you want your images available for use by Kubernetes,
```

2022-03-01 16:10 UTC, jtravee commented on docs/how-to-guides/working-with-images.md
> +nerdctl namespaces are independent and seperate from Kubernetes/kubectl namespaces.
```suggestion
nerdctl namespaces are independent and separate from Kubernetes/kubectl namespaces.
```

2022-03-01 16:10 UTC, jtravee commented on docs/how-to-guides/working-with-images.md
> +To build an image for use with Kubernetes specify the `k8s.io` namespace.
```suggestion
To build an image for use with Kubernetes, specify the `k8s.io` namespace:
```

2022-03-01 16:12 UTC, jtravee requested changes

2022-03-01 16:12 UTC, jtravee commented on docs/how-to-guides/working-with-images.md
> +Unlike docker, containerd features its own namespaces, by default images are stored in the `default` namespace.
```suggestion
Unlike docker, containerd features its own namespaces; by default, images are stored in the `default` namespace.
```

2022-04-19 21:15 UTC, jtravee commented
Closing in favor or [#64](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/64) which includes feedback from the RD team.

2022-04-19 21:15 UTC, closed without merging