Added a Tutorial page on debugging apps with VS Code docker extension
rancher-sandbox/docs.rancherdesktop.io pull request #34
Opened 2022-02-28 17:12 UTC by gunamata

Signed-off-by: Gunasekhar Matamalam <gunasekhar.matamalam@suse.com>

2022-02-28 17:40 UTC, evertonlperes approved these changes
LGTM - Works nicely on macOS

2022-03-01 16:00 UTC, jtravee requested changes

2022-03-02 21:24 UTC, gunamata commented on docs/tutorials/vs-code-docker.md
> +### Steps to debug a sample application running within a container.
Modified per your suggestion.

2022-03-02 21:24 UTC, gunamata commented on docs/tutorials/vs-code-docker.md
> +6. Open the command palette (Ctrl+Shift+P, F1, or Cmd+Shift+P) and run "Add Docker Files to Workspace". Since this is an Express app, Select `Node.js` as Application Platform,  `3000` or any other av
Modified per your suggestion.

2022-03-02 21:24 UTC, gunamata commented on docs/tutorials/vs-code-docker.md
> +10. On some machines, the firewall settings might prevent the debugging process from establishing a connection between the host and the container processes. In this case, you can add a firewall rule
Modified per your suggestion.

2022-03-02 22:55 UTC, jtravee approved these changes

2022-03-02 23:15 UTC, merged