Added a faq item for the container volume paths information
rancher-sandbox/docs.rancherdesktop.io pull request #72
Opened 2022-05-09 23:20 UTC by gunamata

Signed-off-by: Gunasekhar Matamalam <gunasekhar.matamalam@suse.com>

2022-05-09 23:30 UTC, mook-as requested changes

2022-05-09 23:30 UTC, mook-as commented on docs/faq.md
> +#### **Where does Rancher Desktop actually put the data volumes?**
```suggestion
#### **Q: Where does Rancher Desktop actually put the data volumes?**
```

2022-05-09 23:30 UTC, mook-as commented on docs/faq.md
> +containerd: \\wsl$\rancher-desktop-data\var\lib\nerdctl\dbb19c5e\volumes\<namespace>
FWIW, [nerdctl docs](https://github.com/containerd/nerdctl/blob/b235a096085039ad4238ee5c70dbf6bfa11da76f/docs/dir.md#datarootaddrhash) explain where `dbb19c5e` comes from; I think that means it's going to be a constant for us.

2022-05-09 23:30 UTC, mook-as commented on docs/faq.md
> +Navigate to the path provided below in the VM(lima), depending on the active container runtime. You can use `rdctl shell` to access these paths in the VM.
```suggestion
Navigate to the path provided below in the VM, depending on the active container runtime. You can use `rdctl shell` to access these paths in the VM.
```

Alternatively, _… in the (lima) VM_.

2022-05-09 23:35 UTC, gunamata commented on docs/faq.md
> +#### **Where does Rancher Desktop actually put the data volumes?**
Good catch. Thank you :).

2022-05-09 23:36 UTC, gunamata commented on docs/faq.md
> +Navigate to the path provided below in the VM(lima), depending on the active container runtime. You can use `rdctl shell` to access these paths in the VM.
Modified per your suggestion.

2022-05-10 00:07 UTC, mook-as approved these changes

2022-05-10 00:07 UTC, merged